application: appid
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: index.php

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: 30d

- url: /ip.php
  script: ip.php

- url: /tz.php
  script: tz.php

- url: .*
  script: index.php
